name: Template - Project Build/Test

on:
  workflow_call:
    inputs:
      name:
        description: "Display Name of Job"
        required: true
        type: string
      source-directory:
        description: "Relative path to source directory folder"
        required: true
        type: string
      source-project:
        description: "File name of .csproj file in source directory folder"
        required: true
        type: string
      test-directory:
        description: "Relative path to test directory folder"
        required: true
        type: string
      test-project:
        description: "File Name of .csproj file in test directory folder"
        required: true
        type: string

jobs:
  project-build-test:
    name: ${{ inputs.name }} (${{ matrix.dotnet-target-framework }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-target-framework: ["net8.0", "net9.0"]
        include:
          - dotnet-install-framework: 8.0.x
            dotnet-target-framework: net8.0
          - dotnet-install-framework: 9.0.x
            dotnet-target-framework: net9.0
    env:
      source-directory: ${{ inputs.source-directory }}
      source-project: ${{ inputs.source-project }}
      test-directory: ${{ inputs.test-directory }}
      test-project: ${{ inputs.test-project }}
      source-target-framework: "netstandard2.1"

    steps:
      - uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-install-framework }}
          include-prerelease: true

      - name: Install Dependencies
        run: |
          dotnet restore ${{ env.source-directory }}/${{ env.source-project }}
          dotnet restore ${{ env.test-directory }}/${{ env.test-project }} -p:TargetFramework=${{ matrix.dotnet-target-framework }}

      - name: Build
        working-directory: ${{ env.source-directory }}
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ${{ env.test-directory }}
        run: dotnet test -p:TargetFramework=${{ matrix.dotnet-target-framework }} --no-restore --verbosity normal
